### PR TITLE
add dockerfile

### PR DESCRIPTION
**Pull request by TomasTomecek**
Signed-off-by: Tomas Tomecek <ttomecek@redhat.com>

### CODE REVIEW

**Review by KarstenHopp — COMMENTED** [review]
Just to set a good example for everyone looking at this, please add ' && dnf clean all' to the end of the RUN statement.

**Comment by TomasTomecek** [comment]
done

**Comment by TomasTomecek** [comment]
@KarstenHopp rebased

**Comment by TomasTomecek** [comment]
thanks!

**Pull request merged**
